[build]
command = "pnpm run build"
publish = "out"

[build.environment]
NODE_ENV = "production"

[context.production.environment]
PREVIEW = "false"

[context.branch-deploy.environment]
PREVIEW = "true"

[context.deploy-preview.environment]
PREVIEW = "true"
