name: Run FlakeHub docs site tests

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - uses: DeterminateSystems/flake-checker-action@main
        with:
          fail-mode: true
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix flake check --all-systems
      - name: Check sensitivity using Alex
        run: |
          nix develop --command check-sensitivity
      - name: Check style using Vale
        run: |
          nix develop --command lint-style
